### ISSUE TITLE
Handle binary fileupload segmentField conflicts automatically

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh-incubator#157]
The filename of binary fields should automatically be updated when a conflict with an existing segmentField has been detected. The uniqueness of the segmentField should be guaranteed.

# Tasks
* [ ] Add code to make segmentField for binary fields unique
* [ ] Make the rename operation optional
* [ ] Define and document the rename pattern
