### ISSUE TITLE
Mesh in-transit encryption

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh-incubator#231]
It would be useful to support in-transit encryption for Mesh.

# Tasks

* [ ] Handle SSL flag in PluginContext
* [x] Fix SSL support for Servers
* [ ] Add encryption support for monitoring server
