### ISSUE TITLE
Gentics Mesh Documentation

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh-incubator#70]
We still need to improve our documentation. Here are some points and task which will improve the existing documentation.

Good documentation examples are _imho_:

* [PHP](http://php.net/manual/en/) 
* [jQuery](http://api.jquery.com/)
* [Vert.x](http://vertx.io/docs/)

## Tasks 

- [ ] Raw Search - Document paging , language filtering behavior. See https://gitter.im/gentics/mesh?at=5f7cba131adcf94d3f052863
- [ ] Search queries - The listed search queries do not work out of the box. Maybe the fields changed?
- [x] GraphQL docs - Add more GraphQL examples and docs on how to use GraphQL with Gentics Mesh. 
- [ ] Add documentation on graphql schema. Automatically assert that listed queries work against current demo.
- [x] Add backup/restore docs 
- [x] Document ETag, CORS
- [ ] Document Error Code handling
- [ ] Document old UI - Add info about new UI - Add screenshot of old and new UI
- [x] Add missing H1 to docs @jotschi
- [ ] Darken font in order to make it more readable @bernhardriegler 
- [ ] Increase padding to make it more readable  @bernhardriegler 
- [x] Make images responsive @bernhardriegler 
- [ ] Remove borders from tips and notes @bernhardriegler 
- [x] What can we do about huge code examples? @bernhardriegler 
- [ ] Add alt text attributes to images @aschauerhuber 
- [ ] Check table width @aschauerhuber 
- [ ] Properties tables could perhaps be grouped by tabs / akkordion @bernhardriegler 
- [ ] Improve error response and/or docs regarding [Elasticsearch integration](https://getmesh.io/docs/building-blocks/#_elasticsearch_integration) (posting invalid elasticsearch property in payload to ```/schemas``` is not perfectly understandable) @pschulzk
